#!/bin/bash 

# Shebang Notation : This tells the script with interpretor this script has to be executed.
# There can only be one interpretor per script and that should always be the first line of the script.

echo Welcome To Bach Scripting 

# This is how we can execute the scripts
